### ISSUE TITLE
 InvalidVersionSpecError: ==1.*

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/ipywidgets-feedstock#51]
In my Windows docker build logs I'm noticing errors like below:
```
Collecting package metadata:
...working
... Skipping conda-forge/win-64::ipywidgets-5.2.3-py36_0 due to InvalidVersionSpecError: ==1.*

Skipping conda-forge/win-64::ipywidgets-5.2.3-py27_0 due to InvalidVersionSpecError: ==1.*

Skipping conda-forge/win-64::ipywidgets-5.2.3-py35_0 due to InvalidVersionSpecError: ==1.*

done
Solving environment:
...working
... failed
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda\models\version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '>=1.2.6,==1.*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda\models\version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '==1.*'

During handling of the above exception, another exception occurred:
```

Haven't had time to investigate yet but wanted to post it so it didn't get lost.

**Comment by dhirschfeld** [comment]
ping @jasongrout, @jakirkham

If conda doesn't like that version spec perhaps this old package should be moved to broken?
```
λ conda info conda-forge::ipywidgets=5.2.3=py36_0

ipywidgets 5.2.3 py36_0
-----------------------
file name   : ipywidgets-5.2.3-py36_0.tar.bz2
name        : ipywidgets
version     : 5.2.3
build string: py36_0
build number: 0
channel     : https://conda.anaconda.org/conda-forge/win-64
size        : 67 KB
arch        : x86_64
constrains  : ()
license     : BSD 3-clause
md5         : e7d4bcdc03bdfad7c972c40ed1483ea0
platform    : win32
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/ipywidgets-5.2.3-py36_0.tar.bz2
dependencies:
    ipykernel >=4.2.2
    ipython >=4.0.0
    python 3.6*
    traitlets >=4.2.1
    widgetsnbextension >=1.2.6, ==1.*
```

**Comment by jasongrout** [comment]
Can confirm:

```
% conda create -n del-w523 ipywidgets=5.2.3
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ipywidgets=5.2.3
  - widgetsnbextension[version='>=1.2.6,==1.*']

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by jasongrout** [comment]
A fixed package was released and so far has been built on linux64. I'm waiting for it to be built for os x so I can test to make sure the fix works before closing this.

**Comment by dhirschfeld** [comment]
Thanks for the quick fix!

**Comment by jasongrout** [comment]
It's been a few days now, and still only the linux packages are built. Not sure what is going on there with building the windows/macOS packages...

**Comment by dhirschfeld** [comment]
This would explain why I'm still seeing the error!
Maybe the slow build is to do with the big rebuild? 
https://conda-forge.org/status/

**Comment by jasongrout** [comment]
>  Maybe the slow build is to do with the big rebuild?

Very possible, I'd imagine!

**Comment by ocefpaf** [comment]
@dhirschfeld I'm assuming you are not on Linux b/c those got uploaded:

https://anaconda.org/conda-forge/ipywidgets/files

The issue here is that the target branch for that release does not have the new tokens for Travis-CI and AppVeyor. Fixing this in a moment...

**Comment by dhirschfeld** [comment]
I no longer get the error now so will close as  fixed!

**Comment by jasongrout** [comment]
Great!
